---
manager:
  include_meta: False
  max_workers: 2

providers:
  zones:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
    enforce_order: False

  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN
    # Manage Page Rules (URLFWD) records
    # I don't use this and Account API tokens don't support this anyway
    pagerules: false

zones:
  maltsaar.ee.:
    sources:
      - zones
    targets:
      - cloudflare
  wavy.ws.:
    sources:
      - zones
    targets:
      - cloudflare
